### ISSUE TITLE
Customized concepts embedding for ov detection

### ISSUE THREAD

**Issue by Izzysh7** [microsoft/RegionCLIP#27]
Hi, thanks for your great reaserch! There is still something I feel confused. 

I want to use this job to do ov detection on my costomized images. I follow the steps in readme, prepare concepts.txt and turn it into a .pth file. After that, I simply change the emb_path from 
MODEL.CLIP.TEXT_EMB_PATH ./pretrained_ckpt/concept_emb/lvis_1203_cls_emb.pth \
MODEL.CLIP.OPENSET_TEST_TEXT_EMB_PATH ./pretrained_ckpt/concept_emb/lvis_1203_cls_emb.pth \
into
MODEL.CLIP.TEXT_EMB_PATH ./pretrained_ckpt/concept_emb/concept_embeds.pth \
MODEL.CLIP.OPENSET_TEST_TEXT_EMB_PATH ./pretrained_ckpt/concept_emb/concept_embeds.pth \
However, I got boxes with unexpected text. 

For example, my concepts.txt include 7 objects：cat, panda, potato, bear, car, person, toy, sail
But the boxes are recognized as unexpected 7 objects：almond, aerosol_cal, alligator, air_conditioner, alarm_clock, ambulance, alcohol, airplane

I saw some similar issues, and one of them mentioned that we need a json file to specify object class names. Is this true?

**Comment by Izzysh7** [comment]
In more details, I check the size of "openset_test[1]" in detectron2\modeling\roi_heads\fast_rcnn.py, line 469, which should be [#openset_test_num_cls, 1024]. In my case, the size of "openset_test[1]" is torch.Size([1024])

**Comment by YiwuZhong** [comment]
@Izzysh7 Yes, the problem comes from the mismatch between predicted class id and class name in visualization process. 

After replacing the default concept embeddings with your custom ones, our model is already able to detect the custom objects (by matching region features to your custom embeddings). Then the only effort is to correctly visualize the class names given the predicted class id. You could look into the visualization code which was directly derived from Detectron2.
