### ISSUE TITLE
Pre-training data and usage of RegionCLIP

### ISSUE THREAD

**Issue by Jeff-LiangF** [microsoft/RegionCLIP#3]
@jwyang Hi, thanks for your great work and well organized repo! May I ask two questions?

1. The pre-training dataset of RegionCLIP, as mentioned in the paper: 

> During pretraining, the default student model and teacher model were ResNet50 [22] from pretrained CLIP.

Does it mean that RegionCLIP is actually using CLIP400M + CC3M data? The textual encoder of RegionCLIP is the same as the CLIP. I am wondering the visual encoder is initialized with CLIP pre-trained model or from scratch. 

2. The usage of CC pre-trained regionCLIP. Is the `regionclip_pretrained-cc_{rn50, rn50x4}.pth` ckpt the same format as the original CLIP? If yes, it would be very easy for me to try your model on my task. 

Thanks!

**Comment by YiwuZhong** [comment]
Hi Jeff,

Thanks for your interests on our work. Let me try to answer your questions and maybe Jianwei will add comments later.

1. We used pre-trained CLIP as initialization, as mentioned in the Figure 2 and section 3.2.1 in our paper. CLIP400M was used to learn **image-level** representation (analogy to backbones pre-trained on ImageNet). The pre-trained CLIP serves as the starting point of our RegionCLIP. A small dataset (CC3M) was used to learn **region-level** representation (analogy to detectors trained on detection datasets). When there are more computational resources and more available data, RegionCLIP can be trained on a larger scale of data, such as CLIP400M.

2. The checkpoint file has the same parameter slots as original CLIP. Since the checkpoint file is a dictionary (keys as parameter names, values as the trained weights), you can simply filter the prefix of dictionary keys (e.g., "backbone.xxx"). So I think it should be easy to use on your task.

Best,
Yiwu

**Comment by Jeff-LiangF** [comment]
@YiwuZhong Thanks for your comments. Problem solved!

**Comment by Jeff-LiangF** [comment]
Hi @YiwuZhong , I am now parsing your pre-trained `regionclip_pretrained-cc_rn50x4.pth` model. If I understand correctly, the keys begin with `backbone.` belong to the **new** visual encoder (originally begins with `visual.` ), the keys begin with `lang_encoder.` belongs to the language encoder. Am I correct? Thanks!

**Comment by YiwuZhong** [comment]
Yes, exactly. Your understanding is correct.

**Comment by Jeff-LiangF** [comment]
Got it! Thanks!
