### ISSUE TITLE
API or scripts for extracting regional features.

### ISSUE THREAD

**Issue by zfchenUnique** [microsoft/RegionCLIP#5]
Hi!
     Thanks for your exciting work!
      I would like to use RegionCLIP to extract regional features for images and match them with sentences.
      Is there any API or demo scripts that I could refer to simply achieve this goal like the CLIP model (https://github.com/openai/CLIP.git)?

Regards,
Zhenfang

**Comment by YiwuZhong** [comment]
Hi Zhenfang, thanks for your interests in our work. So far, we have released the scripts to [extract region features from custom images](https://github.com/microsoft/RegionCLIP#extract-region-features). 

The region features will be saved in a local file `.pth` per image. For sentences, since our work froze the language encoder of CLIP, you can directly use the CLIP API to encode the custom sentences you have. Then the matching can be done between the sentence embeddings and our region features in the local files.

**Comment by zfchenUnique** [comment]
Thanks for your unbelievable response speed and will try it soon!
