### ISSUE TITLE
'Non-existent config key: MODEL.CLIP'.

### ISSUE THREAD

**Issue by lanternjx** [microsoft/RegionCLIP#72]
'Non-existent config key: MODEL.CLIP'., case I strictly followed your installation, but it comes that your version is wrong, so I installed original Detectron2. But original Detectron2 'Non-existent config key: MODEL.CLIP'. so what should i do to install your detectron

**Comment by YiwuZhong** [comment]
Please refer to issue #60. The solution is to downgrade the version of setuptools: pip install setuptools==59

**Comment by Xuefei98** [comment]
Hi Yiwu, I am facing the same error and tried to downgrade the setuptools to 59.0.1 but the error still exist. I am not sure what are the other possible solutions here? Thank you!

**Comment by YiwuZhong** [comment]
@Xuefei98 Please make sure that you strictly follow the instruction and the master branch. I've tried on my side and it works well.

**Comment by Lim208** [comment]
I solved the problem. It is because the author modified the detectron2 code, the code will be overwritten when detectron2 is installed. So, when you install detectron2, you have to move the modified code. In my case, 
I had to move the following folders from the author's detectron2 folder to the newly installed detectron2 folder.

detectron2/config
detectron2/data
detectron2/layers
detectron2/modeling
detectron2/structures
detectron2/utils

**Comment by kdjflsdjf1159** [comment]
I solved the problem. It is because the author modified the detectron2 code, the code will be overwritten when detectron2 is installed. So, when you install detectron2, you have to move the modified code. In my case,
I had to move the following folders from the author's detectron2 folder to the newly installed detectron2 folder.

detectron2/config
detectron2/data
detectron2/layers
detectron2/modeling
detectron2/structures
detectron2/utils
